### DISCUSSION TITLE
Release 0.3 : Configuration data source

### DISCUSSION THREAD

**Discussion by 42atomys** [42atomys/webhooked#37] [Announcements]
# NEW : Configuration data source

Configuration section can be now loaded via multiple sources at same time, with no breaking change is operated in `v1alpha1` configuration file. The current configuration file still working but receive a lot of new possibility for end user and devs (for adding new storage or configuration fields).

Configuration example with environment variable data source
```yaml
apiVersion: v1alpha1
specs:
- name: exampleHook
  entrypointUrl: /webhooks/example
  security:
  - getHeader:
      name: X-Hook-Secret
  - compareWithStaticValue:
      # Accept current configuration with in plain text value
      value: 'developmentKey'
      # Accept now a new field : valueFrom because compareWithStaticValue
      # is now a valuable.Valuable
      valueFrom:
        envRef: SECRET_TOKEN
  storage:
  - type: redis
    specs:
      host: redis
      port: 6379
      database: 0
      # Same example here, its possible to use plain text directly on root
      password: '123'
      # Or use the new valuable.Valuable object
      password:
        valueFrom:
          envRef: REDIS_PASSWORD
      key: example-webhook
```

## What's Changed
* feat: Add configuration data source by @42Atomys in https://github.com/42Atomys/webhooked/pull/36

**Full Changelog**: https://github.com/42Atomys/webhooked/compare/0.2...0.3

<hr /><em>This discussion was created from the release <a href='https://github.com/42Atomys/webhooked/releases/tag/0.3'>0.3</a>.</em>
