### DISCUSSION TITLE
Release 0.4 : Security Pipeline

### DISCUSSION THREAD

**Discussion by 42atomys** [42atomys/webhooked#41] [Announcements]
# NEW : Security pipeline

Now you can code your security pipeline yourself directly on configuration file. Example below with github webhook security

```yaml
- name: github
  entrypointUrl: /webhooks/github
  security:
  - generate_hmac_256:
      id: signature
      inputs:
      - name: payload
        value: '{{ .Inputs.payload }}'
      - name: secret
        valueFrom:
          envRef: GITHUB_WEBHOOK_SECRET 
  - header:
      id: headerSignature
      inputs:
      - name: headerName
        value: X-Hub-Signature-256
  - compare:
      inputs:
      - name: first
        value: '{{ .Outputs.headerSignature.value }}'
      - name: second
        value: 'sha256={{ .Outputs.signature.value }}'
  storage: []
``` 
All securities built-ins is available here : https://github.com/42Atomys/webhooked/wiki/Security

## What's Changed
* feat/storage rabbitmq by @rgaiffe in https://github.com/42Atomys/webhooked/pull/40
* feat(security/pipeline): Add Pipeline to add more possibilities to the security builder by @42Atomys in https://github.com/42Atomys/webhooked/pull/38

**Full Changelog**: https://github.com/42Atomys/webhooked/compare/0.3...0.4

<hr /><em>This discussion was created from the release <a href='https://github.com/42Atomys/webhooked/releases/tag/0.4'>0.4</a>.</em>
