### ISSUE TITLE
feat: allow construction of postgres request like formatting module

### ISSUE THREAD

**Issue by 42Atomys** [42Atomys/webhooked#106]
### Is your feature request related to a problem? Please describe

Actually the postgres configuration has really basic and dont allow us to do anything. 

```yaml
  # In which table do you want to store the data
  tableName: 'webhooks_deliveries'
  # In which column do you want to store the data (data is sent in string format on this field)
  dataField: 'raw_data'
```

the reflected code behind is
```go
request := fmt.Sprintf("INSERT INTO %s(%s) VALUES ($1)", c.config.TableName, c.config.DataField)
```
We cant perform an update, a delete, base the updated value or inserted value on some part of the payload. 

### Describe the solution you'd like

To be able to use the same formating module in storages like redis and postgres to allow to do all actions according to the specs provided in the configuration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
