### ISSUE TITLE
Security Factory: compareWithGeneratedHMAC

### ISSUE THREAD

**Issue by 42Atomys** [42Atomys/webhooked#21]
Add a factory that allows to compare 2 inputs with a generated HMAC. 

Useful for Github or Twitch webhooks

Example of config (not final)
```yaml
  security:
  - getHeader:
      name: X-Hook-Secret
  - compareWithGeneratedHMAC:
      secret: '{{ .env.HOOK_SECRET }}'
      algorithm: sha256
```
