### ISSUE TITLE
feat: Load configuration part from environment to add more security

### ISSUE THREAD

**Issue by 42Atomys** [42Atomys/webhooked#34]
**Is your feature request related to a problem? Please describe.**
Currently all configuration is loaded via the static configuration file. However it contains information like passwords or tokens that must be private and secure at least.  

**Describe the solution you'd like**
Readable passwords and tokens in the config file

**Describe alternatives you've considered**
Possibility to load some parts of the config via environment variables. Example of configuration file with dynamic values:

```yaml
apiVersion: v1alpha1
specs:
- name: exampleHook
  entrypointUrl: /webhooks/example
  security:
  - getHeader:
      name: X-Hook-Secret
  - compareWithStaticValue:
      valueFrom:
        envRef:
          name: 'XHOOKSECRET_TOKEN_VALUE'
  storage:
  - type: redis
    specs:
      host: localhost
      port: '6379'
      username:
        valueFrom:
          envRef:
            name: 'REDIS_USERNAME'
      password:
        valueFrom:
          envRef:
            name: 'REDIS_PASSWORD'
      database: 0
      key: foo
```
